manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Shoxx98
      url-base: https://github.com/Shoxx98
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-unicode
      remote: Shoxx98
      revision: v0.3 
  self:
    path: config
